### ISSUE TITLE
GodMode9i Meditation Error on boot

### ISSUE THREAD

**Issue by ChampionLeake** [RocketRobz/GodMode9i#2]
When holding the Y button during the logo on next boot, to disable Slot-1 access, GodMode9i still tends to crash the application itself. This also occurs when Slot-1 is inserted and when it's not. 

GodMode9i seems to crash no matter what you do either holding the Y button or not even when Slot-1 is inserted or not.

EDIT: This is for GodMode9i v1.1.0

**Comment by RocketRobz** [comment]
Fixed in 8a9af49

**Comment by crensyhanilas** [comment]
won't fix for me! Reopen this issue
