### ISSUE TITLE
[Suggestion] NAND operations.

### ISSUE THREAD

**Issue by maciak** [RocketRobz/GodMode9i#22]
Hi,
Would it be possible to make any NAND operations available like in the original GM9? Like copy, move, remove or just browse, Any way of getting your NAND ID or any other like ConsoleID, CID?

**Comment by FlameKat53** [comment]
This would be somewhat dangerous, but we could get console ID from RAM iirc. (though it would be messed up some)

**Comment by RocketRobz** [comment]
Implemented by https://github.com/RocketRobz/GodMode9i/commit/bf53a3c037279bd9a046057d7e66706fbc58baf0
