### ISSUE TITLE
Read gamecards

### ISSUE THREAD

**Issue by TheCoder3156** [RocketRobz/GodMode9i#23]
GodMode9i should be given the ability to read game cards to get legal dumps.

**Comment by RocketRobz** [comment]
As of currently, I dunno how to implement that. :P

**Comment by TheCoder3156** [comment]
I’m going to try to submit a pr with functionally. I’ll leave this open in case I need help understanding your code.

**Comment by TheCoder3156** [comment]
I take it back. Libnds does have card reading support but does not have examples. This is going to be fun.

**Comment by dubbz82** [comment]
@TheCoder3156 - just curious any progress on this?

**Comment by TheCoder3156** [comment]
Not really... I submitted an issue on the devkitpro libnds example page for documentation a while back. I believe libnds does have the capability to do so it's just very undocumented.

**Comment by mariomadproductions** [comment]
If you are on DS/lite you can use wooddumper. If you are on DSi you can also use the wooddumper "port" to dump most carts.

**Comment by TheCoder3156** [comment]
Could you give me a link for the dsi? I think I tried that and it didn't work. Plus if it's not open source then it's useless to us.

**Comment by TheCoder3156** [comment]
@RocketRobz I just found out the other day you created your own fork of libnds. Could you attempt to document the cardWriteAndRead function?

**Comment by FlameAlt53** [comment]
i think this is the section with the source code that dumps the game cards on GodMode9 (d0k3's of course)

https://github.com/d0k3/GodMode9/tree/master/arm9/source/gamecart

**Comment by TheCoder3156** [comment]
Godmode9i isn’t based on godmode9 so this probably wouldn’t work. I’ve already considered this too.

**Comment by mariomadproductions** [comment]
Its still wise to follow GodMode9's code as its the most up-to-date and probably most used DS gamecart dumper.

**Comment by FlameAlt53** [comment]
> Godmode9i isn’t based on godmode9 so this probably wouldn’t work. I’ve already considered this too.

yes, i know that, but it may help with dumping carts as MarioMadProductions said "> as its the most up-to-date and probably most used DS gamecart dumper."

**Comment by RocketRobz** [comment]
Added in v2.0.0.
