### ISSUE TITLE
gbc backup on the nds light possible ?

### ISSUE THREAD

**Issue by flutterbrony** [RocketRobz/GodMode9i#25]
Hi ! I'm wondering if it is possible to detect and backup gbc cartridge (or at least the save) because I'm loosing my pokémon saves on some of my cartridge. 
I tried to backup it with gba backup tools, I opened my cartridge and a fake one, I cut some part so the fake cartridge would fit in the ds slot2, then I put my pokemon games in it, but gba backup tool saw a 1MB memory with a weird name for the game, and no saves :/
I don't know if it would even be possible to read it that way, maybe they work totally differently, and it's not possible at all :/

**Comment by dubbz82** [comment]
It's my understanding that gbc carts run on a different voltage and use a physical switch in the gab to support this.  If my understanding is in fact correct this won't work.

**Comment by RocketRobz** [comment]
@flutterbrony Try this build of GM9i. It can do a ROM dump regardless if the selection shows a `[X]` or not.

[GodMode9i_gbcdumptest.zip](https://github.com/RocketRobz/GodMode9i/files/2659448/GodMode9i_gbcdumptest.zip)

**Comment by flutterbrony** [comment]
How do I backup the cartridge ?
I tried with a gba one first, I had this on the top screen :
[root]__________________________{time}
GBA GAMECART


the first line  was green, and the second one was white
on the bottom screen, I have this :
GBA GAMECART
<GBA Game>



GodMode9i v1.3.4
R+B - Remount Flashcard
POWER - Poweroff

I thought pressing A would do the backup, but I have the feeling something is wrong, (and I tried every button, they does nothing, except a blink on the bottom screen when I press UP or DOWN or R+B :/

I also checked the datasheet of a gba and a gbc cartridge, and as @dubbz82 stated, it should not work with a gbc cartridge because it require 5V while the gbc only 3.3V. Maybe I could try with a little mod to send the 5V to the cartridge by disconnecting VCC and GND on the ds board in case there is a fuse that could burn from this.
The physical switch in the GameBoy Advance is in fact for selecting the power input, and on wich bios/cpu it should start. I doubt the ds would be able to deliver 5V to the slot2 :/

**Comment by RocketRobz** [comment]
Press A on `GBA GAMECART`, then when asked to back-up/dump, insert the cartridge, then proceed with the backup.

**Comment by flutterbrony** [comment]
That's what I am doing, but nothing happens, it's not asking me anything. However, it work well on my dsi, but it doesn't have any slot2

**Comment by RocketRobz** [comment]
Are you using the `gbcdumptest` build I uploaded?

**Comment by flutterbrony** [comment]
Yes, I thing it's maybe an issue with my flashcard ?

**Comment by RocketRobz** [comment]
If you can't browse your flashcard, then yes.

**Comment by flutterbrony** [comment]
I'll try to search with the other flashcard I have, it it is just a slow one (5 minutes just to load a game :/) and I have to find where I put it the last time I used it

**Comment by RocketRobz** [comment]
btw, just to verify, are you using TWiLight Menu++ to launch GM9i on your flashcard?

**Comment by flutterbrony** [comment]
Nope, Not on my ds light. I couldn't get TWiLight Menu++ to run on it
I just get the unknown r4 to boot, it seems it can even be run on the dsi., I'll try the gbcdumptest file you uploaded with it. If it doesn't work, I'll search for another flashcart

**Comment by FlameKat53** [comment]
Hello, I tried this out, and it dumps a 32MB .gba file, which doesn’t have any code from the game I tried to dump as viewed in a Hex Editor. and NO$GBA gives errors. So I do not think this is possible. Also, when changed to a .gb or .gbc, it will cause a guru meditation error when loading it via TWiLight Menu++ & Gameyob

**Comment by FlameKat53** [comment]
So, should this be closed?

**Comment by yyoossk** [comment]
Can GodMode9i_gbcdumptest be improved to be able to backup gbc via wifi like gbaxxdumper?
