### ISSUE TITLE
Renaming file to a name containing spaces results in odd behaviour

### ISSUE THREAD

**Issue by gingerbeardman** [RocketRobz/GodMode9i#26]
I ripped a cart using Wooddumper for HiyaCFW, and wanted to rename the resulting file.

- I named it as follows: `True Swing Golf (U).nds`
- It displayed in GM9i as `True`
- I did X+R to rename and it instantly finished and dropped me back at file list
- It displayed in GM9i as `Swing`
- I did X+R to rename and it instantly finished and dropped me back at file list
- It displayed in GM9i as `Golf`
- I did X+R to rename and it instantly finished and dropped me back at file list
- It displayed in GM9i as `(U).nds`
- I did X+R to rename and chose `True_Swing_Golf_(U).nds`
- It displayed in GM9i correctly

**Comment by Epicpkmn11** [comment]
This was fixed in #21
Can you make a new release @RocketRobz ?

**Comment by RocketRobz** [comment]
Done. :P
