### ISSUE TITLE
Please do *not* attempt to maintain an independent libnds fork.

### ISSUE THREAD

**Issue by WinterMute** [RocketRobz/GodMode9i#29]
At per title.

This kind of thing hurts *everyone* please don't do it.

**Comment by FlameKat53** [comment]
Why

**Comment by RocketRobz** [comment]
I made a PR at the libnds repo: https://github.com/devkitPro/libnds/pull/34
Once this is merged, I will delete my fork.

**Comment by FlameKat53** [comment]
Oh, I didn’t realize that :P

**Comment by RocketRobz** [comment]
Since I deleted my libnds fork, I will close this.
