### ISSUE TITLE
Black screen on 3DS version

### ISSUE THREAD

**Issue by daemonspudguy** [RocketRobz/GodMode9i#35]
I can't launch it on my N3DSXL, it just leaves me on a black screen and I have to force-reboot.

**Comment by RocketRobz** [comment]
TWL_FIRM is broken on your console.
Please follow this guide to fix it: https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by daemonspudguy** [comment]
TWiLightMenu++ boots up, NDS carts boot up, Four Swords boots up, (yes I am one of the last human beings to own it) GM9i is the only one @RocketRobz

**Comment by RocketRobz** [comment]
Are you using EmuNAND?

**Comment by daemonspudguy** [comment]
My SD card is only 4 gigs, so no.

**Comment by RocketRobz** [comment]
Try launching it's .nds file in TWiLight Menu++.

**Comment by daemonspudguy** [comment]
Okay...

**Comment by daemonspudguy** [comment]
The NDS loads

**Comment by RocketRobz** [comment]
idk what's wrong then...

**Comment by daemonspudguy** [comment]
Do you have a 3ds? If so, try testing the latest CIA on that.

**Comment by RocketRobz** [comment]
Yeah, it works for me.

**Comment by daemonspudguy** [comment]
Bad CIA transfer, maybe? I'll try to reinstall it.

**Comment by RocketRobz** [comment]
How did you copy it over?

**Comment by daemonspudguy** [comment]
FTP

**Comment by daemonspudguy** [comment]
It works now.

**Comment by RocketRobz** [comment]
Nice!
