### ISSUE TITLE
GodMode9i Powering off the console [From AutoBoot Method]

### ISSUE THREAD

**Issue by ChampionLeake** [RocketRobz/GodMode9i#4]
When booting GodMode9i (as an autoboot method  with**_bootthis.dsi_** and holding X), if Slot-1 is inserted and you're not holding the Y button to disable cart access, the DSi will shut itself off.

EDIT: Running GodMode9i from DSiWarehax doesn't have this issue

**Comment by RocketRobz** [comment]
Can you see if v1.3.0 fixes the issue?

**Comment by ChampionLeake** [comment]
Yes it did. I'll close this thread :D
