### ISSUE TITLE
Stuck on "mounting drive(s)" with hiyaCFW

### ISSUE THREAD

**Issue by frnklnchng** [RocketRobz/GodMode9i#53]
Tested on DSi, FAT 32 SD card. Application just freezes on start at "mounting drive(s)".

**Comment by RocketRobz** [comment]
Try holding Y before the freeze.

**Comment by frnklnchng** [comment]
Tried that - still stuck at "mounting drives". I tried just leaving it there for a few minutes and no progress.

**Comment by RocketRobz** [comment]
Try immediately removing the SD card, after the GM9i logo shows.

**Comment by frnklnchng** [comment]
Still nothing, any other suggestions? I haven't tried running an older release yet.

**Comment by RocketRobz** [comment]
What are you launching GM9i with?

**Comment by frnklnchng** [comment]
Using the latest TWiLight.

**Comment by RocketRobz** [comment]
What are the per-game settings set for GM9i?

**Comment by frnklnchng** [comment]
I'm not sure where I can find that out from, but I haven't been able to run it at all, nor have I changed any settings.

**Comment by RocketRobz** [comment]
In the TWLMenu++ ROM menu, press Y.

**Comment by frnklnchng** [comment]
Gotcha, wasn't sure what you meant. But, I don't get any option for settings when I open the Y menu.

**Comment by papin97** [comment]
I get the same issue (holding Y button doesn't solve the issue).
Here's per-game setting that I use:
- Language: Default
- RAM Disk: None
- Direct Boot: Yes
- Run in: DSi Mode
- ARM9 CPU Speed: 133 MHz (TWL)
- VRAM Boost: On
- Bootstrap: Default

**Comment by RocketRobz** [comment]
It appears the issue is caused by using the app in HiyaCFW.

**Comment by R-YaTian** [comment]
> It appears the issue is caused by using the app in HiyaCFW.

Ha, I think this is because GM9i cannot mount nand after access HiyaCFW.

**Comment by ApacheThunder** [comment]
I've recently updated GodMod9i to the latest build and I'm now experiencing this issue too. However I have GodMode9i setup as DSiWare so I launch it from System Menu and not from HiyaCFW or Twilight.

**Comment by stuffi3000** [comment]
I'm having the same issues. Is there and fix in sight? Or maybe a temporary solution like "hold this button to not mount NAND". Because I have no idea how to apply the fix from @ApacheThunder haha

**Comment by SNBeast** [comment]
I have this same issue. I find that a way to bypass it is to load GodMode9i from Unlaunch.

**Comment by stuffi3000** [comment]
> 
> 
> I have this same issue. I find that a way to bypass it is to load GodMode9i from Unlaunch.

That's a great workaround, thank you!

**Comment by RocketRobz** [comment]
Fixed in v2.4.0, by holding X.
