### ISSUE TITLE
copying to nand

### ISSUE THREAD

**Issue by 3EGaming** [RocketRobz/GodMode9i#54]
Trying to copy a file from SD to nand. it says copying, then the file is gone from clipboard, and not in folder where I was trying to paste.
I'm using flipnote lenny to launch TWiLight menu to launch GodMode9i on EUR DSi

**Comment by NightYoshi370** [comment]
You can't write stuff to NAND

**Comment by 3EGaming** [comment]
why not?

**Comment by 3EGaming** [comment]
will a NAND writing feature ever be added like in GodMode9?
