### ISSUE TITLE
Crash DSi trying launching GodMode9i

### ISSUE THREAD

**Issue by Relwi** [RocketRobz/GodMode9i#55]
Hi, I'm a newbie into this, I'm trying to install Unlaunch following this tutorial: https://dsi.cfw.guide/installing-unlaunch. 
But when I'm in the gallery and I press de Album, the screen go to purple screen and quickly, in green, and my DSi get stuck.
I have the pit, DSi firmware 1.4-1.4.5 EUR version
IDK if this is a GodMode9i problem or my DSi or the pit file.

**Comment by RocketRobz** [comment]
This isn't a GodMode9i issue.
Let's continue this here: https://discord.gg/yD3spjv

**Comment by Relwi** [comment]
Well, it was a sd card problem. I change it and now it works
