### ISSUE TITLE
Wrong power button instructions for 3DS consoles

### ISSUE THREAD

**Issue by zacchi4k** [RocketRobz/GodMode9i#8]
Unlike the DSi, on 3DS consoles you can't press the power button to reboot and hold it to shutdown, which GM9i suggests

**Comment by RocketRobz** [comment]
On 3DS, pressing the power button will reboot into the 3DS HOME Menu, but with the power off screen shown first, where the user can press HOME to return.
Also, holding power button will power off the console on 3DS as well. Works for me on my side.

**Comment by RocketRobz** [comment]
Fixed in 08169fc
