### ISSUE TITLE
File selector wraps around if quick scrolling (D-Pad left/right) overflows

### ISSUE THREAD

**Issue by zacchi4k** [RocketRobz/GodMode9i#9]
Pressing left/right on the D-Pad increments or decrements the selected file index by 10.
If, for example, there are less than 10 entries left, and you press right on the D-Pad, instead of selecting the very last entry (which is what would feel the most natural), it wraps around and selects the very first entry in the list (usually ..). The wrapping around also happens when pressing the left button (when at the top of the list)

**Comment by RocketRobz** [comment]
Fixed by #10
